version: '3.8'

services:
  pwa-app:
    build: .
    ports:
      - "3000:80"
    container_name: rickandmorty-pwa
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html  # Para desenvolvimento (opcional)